"""Initial migration with user extensions

Revision ID: a3edb1bf178e
Revises: 
Create Date: 2026-02-16 20:46:12.100580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3edb1bf178e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Handle Balance
    op.add_column('users', sa.Column('balance', sa.Integer(), nullable=True))
    op.execute("UPDATE users SET balance = 0")
    op.alter_column('users', 'balance', nullable=False)

    # 2. Handle is_blocked
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_blocked = False")
    op.alter_column('users', 'is_blocked', nullable=False)

    # 3. Handle last_activity_at
    op.add_column('users', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE users SET last_activity_at = NOW()")
    op.alter_column('users', 'last_activity_at', nullable=False)

    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))

    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('users', 'last_activity_at')
    op.drop_column('users', 'is_blocked')
    op.drop_column('users', 'balance')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
